Repository kubernetes-sigs/poseidon, pull requests merged in 2018-10, with the labels that each got.

#138 Release events feature
  cmd/poseidon/poseidon.go
  pkg/firmament/affinity.pb.go
  pkg/firmament/coco_interference_scores.pb.go
  pkg/firmament/firmament_scheduler.pb.go
  pkg/firmament/firmament_scheduler.proto
  pkg/firmament/job_desc.pb.go
  pkg/firmament/label.pb.go
  pkg/firmament/label_selector.pb.go
  pkg/firmament/node_affinity.pb.go
  pkg/firmament/pod_affinity.pb.go
  pkg/firmament/pod_anti_affinity.pb.go
  pkg/firmament/reference_desc.pb.go
  pkg/firmament/resource_desc.pb.go
  pkg/firmament/resource_stats.pb.go
  pkg/firmament/resource_topology_node_desc.pb.go
  pkg/firmament/resource_vector.pb.go
  pkg/firmament/scheduling_delta.pb.go
  pkg/firmament/taints.pb.go
  pkg/firmament/task_desc.pb.go
  pkg/firmament/task_final_report.pb.go
  pkg/firmament/task_stats.pb.go
  pkg/firmament/tolerations.pb.go
  pkg/firmament/whare_map_stats.pb.go
  pkg/k8sclient/BUILD
  pkg/k8sclient/events.go
  pkg/k8sclient/k8sclient.go
  pkg/k8sclient/podwatcher.go
  pkg/k8sclient/types.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#136 Adding support for Static PV claim
  pkg/k8sclient/podwatcher.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#137 Adding ephemeral storage support for Poseidon
  pkg/firmament/resource_vector.pb.go
  pkg/firmament/resource_vector.proto
  pkg/k8sclient/nodewatcher.go
  pkg/k8sclient/podwatcher.go
  pkg/k8sclient/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#140 add design docs
  docs/design/images/CPU-Memory-Cost-Model-Diagram.png
  docs/design/images/CPU-Memory-cost-model-and-nodeSelector-in-firmament.png
  docs/design/images/Example-flow-graph-for-node-affinity-soft-and-hard-constraints.png
  docs/design/images/Labels-Mapping-for-storing-Key-Values-and-associated-Task-IDs.png
  docs/design/images/Pod-Affinity-Anti-Affinity-Queue.png
  docs/design/images/Scheduling-Round-Diagram.png
  docs/design/node_affinity_and_selector_for_poseidon.md
  docs/design/node_max-allowed_pods_design.md
  docs/design/pod_affinity_anti-affinity_design.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#141 Add design docs on taints and tolerations, gang scheduling
  docs/design/gang_scheduling.md
  docs/design/images/CPU-Memory-Cost-Model-Diagram-with-a-node-with-1-intolerable-taint.png
  docs/design/images/Relaxed-and-Strict-gang-scheduling.png
  docs/design/taints_and_tolerations_design.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#143 fix `make` after running `dep ensure` and `hack/update-bazel.sh`
  Gopkg.lock
  hack/lib/golang.sh
  hack/make-rules/test.sh
  vendor/k8s.io/kubernetes/hack/cmd/teststale/BUILD
  vendor/k8s.io/kubernetes/hack/cmd/teststale/teststale.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#142 Add spelling check script and fix typos
  Gopkg.lock
  Gopkg.toml
  build/copy-output.sh
  hack/.spelling_failures
  hack/make-rules/verify.sh
  hack/release.sh
  hack/verify-spelling.sh
  pkg/k8sclient/nodewatcher_test.go
  pkg/k8sclient/podwatcher.go
  pkg/k8sclient/podwatcher_test.go
  pkg/stats/poseidonstats.proto
  test/e2e/poseidon_integration.go
  vendor/github.com/client9/misspell/.gitignore
  vendor/github.com/client9/misspell/.travis.yml
  vendor/github.com/client9/misspell/BUILD
  vendor/github.com/client9/misspell/Dockerfile
  vendor/github.com/client9/misspell/Gopkg.lock
  vendor/github.com/client9/misspell/Gopkg.toml
  vendor/github.com/client9/misspell/LICENSE
  vendor/github.com/client9/misspell/Makefile
  vendor/github.com/client9/misspell/README.md
  vendor/github.com/client9/misspell/RELEASE-HOWTO.md
  vendor/github.com/client9/misspell/ascii.go
  vendor/github.com/client9/misspell/case.go
  vendor/github.com/client9/misspell/cmd/misspell/BUILD
  vendor/github.com/client9/misspell/cmd/misspell/main.go
  vendor/github.com/client9/misspell/goreleaser.yml
  vendor/github.com/client9/misspell/install-misspell.sh
  vendor/github.com/client9/misspell/legal.go
  vendor/github.com/client9/misspell/mime.go
  vendor/github.com/client9/misspell/notwords.go
  vendor/github.com/client9/misspell/replace.go
  vendor/github.com/client9/misspell/stringreplacer.go
  vendor/github.com/client9/misspell/stringreplacer_test.gox
  vendor/github.com/client9/misspell/url.go
  vendor/github.com/client9/misspell/words.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
