Repository kubernetes-sigs/poseidon, pull requests merged in 2018-05, with the labels that each got.

#47 Updating Owner file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#48 Add some comments for /pkg
  pkg/firmament/coco_interference_scores.proto
  pkg/firmament/firmament_client.go
  pkg/firmament/firmament_scheduler.proto
  pkg/firmament/label.proto
  pkg/firmament/label_selector.proto
  pkg/firmament/resource_desc.proto
  pkg/firmament/resource_stats.proto
  pkg/firmament/resource_topology_node_desc.proto
  pkg/firmament/resource_vector.proto
  pkg/firmament/scheduling_delta.proto
  pkg/firmament/task_desc.proto
  pkg/firmament/task_final_report.proto
  pkg/firmament/task_stats.proto
  pkg/firmament/whare_map_stats.proto
  pkg/stats/poseidonstats.proto
  pkg/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#12 Replace Mutex with RWMutex increase read efficiency
  cmd/poseidon/poseidon.go
  pkg/k8sclient/nodewatcher.go
  pkg/k8sclient/podwatcher.go
  pkg/k8sclient/types.go
  pkg/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#58 Typo fix misspell
  cmd/poseidon/poseidon.go
  pkg/k8sclient/keyed_queue_test.go
  test/e2e/framework/namespace.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#61 Updating roadmap section of README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#67 Adding docs related to release process
  README.md
  docs/releases/release-process.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#68 Travis config
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#69 cleanup unused codes in hack
  hack/e2e-node-test.sh
  hack/lib/BUILD
  hack/lib/etcd.sh
  hack/lib/init.sh
  hack/lib/protoc.sh
  hack/lib/swagger.sh
  hack/lib/test.sh
  hack/make-rules/BUILD
  hack/make-rules/test-cmd-util.sh
  hack/make-rules/test-cmd.sh
  hack/make-rules/test-e2e-node.sh
  hack/make-rules/test-integration.sh
  hack/make-rules/test-kubeadm-cmd.sh
  hack/make-rules/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#59 E2E test case for CPU cost model
  test/OWNERS
  test/e2e/framework/framework.go
  test/e2e/framework/util.go
  test/e2e/poseidon_integration.go
  test/e2e/predicates.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#74 log a message when delete pod failed
  pkg/k8sclient/k8sclient.go
  pkg/k8sclient/keyed_queue.go
  pkg/k8sclient/nodewatcher.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#75 Fixed a bug in the nodeselector sort method
  hack/make-rules/BUILD
  pkg/k8sclient/podwatcher.go
  test/e2e/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/S

#73 e2e: add node selector test
  test/e2e/framework/util.go
  test/e2e/poseidon_integration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#80 Increasing the default timeout to 60m for the E2E tests
  test/e2e-poseidon-gce.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#70 check the length if kubeVer for maybe panic
  pkg/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#81 Fixing the flags Parse error message in logs
  pkg/config/config.go
  test/e2e/framework/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/XS

#83 Increasing the default timeout to 60m for the local E2E tests
  test/e2e-poseidon-local.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#84 LICENSE: use formal Apache License Content
  LICENSE
Labels: approved, cncf-cla: yes, lgtm, size/L

#86 when wait for running state we should the err
  test/e2e/poseidon_integration.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#82 fix todo:pass the cluster role from env and add err check in e2e
  test/e2e/framework/BUILD
  test/e2e/framework/deployment_util.go
  test/e2e/framework/framework.go
  test/e2e/framework/namespace.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#89 Adding myself to top level owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#90 Correctly updating pod label and node label when an update is received
  pkg/k8sclient/nodewatcher.go
  pkg/k8sclient/podwatcher.go
  test/e2e/poseidon_integration.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#42 add pprof and runtime stack in debugutil
  cmd/poseidon/BUILD
  cmd/poseidon/poseidon.go
  pkg/config/config.go
  pkg/debugutil/BUILD
  pkg/debugutil/debugutil.go
  test/e2e/framework/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/L

#96 add .idea/ to ./gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#97 add instructions about Local Cluster E2E test by local-up-cluster.sh
  docs/devel/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#92 modify README.md file about Local Cluster E2E test
  docs/devel/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#98 Node Affinity and Node Anti-Affinity enhancement related changes.
  Gopkg.lock
  pkg/firmament/BUILD
  pkg/firmament/affinity.pb.go
  pkg/firmament/affinity.proto
  pkg/firmament/coco_interference_scores.pb.go
  pkg/firmament/firmament_scheduler.pb.go
  pkg/firmament/job_desc.pb.go
  pkg/firmament/label.pb.go
  pkg/firmament/label_selector.pb.go
  pkg/firmament/license.txt
  pkg/firmament/node_affinity.pb.go
  pkg/firmament/node_affinity.proto
  pkg/firmament/pod_affinity.pb.go
  pkg/firmament/pod_affinity.proto
  pkg/firmament/pod_anti_affinity.pb.go
  pkg/firmament/pod_anti_affinity.proto
  pkg/firmament/reference_desc.pb.go
  pkg/firmament/resource_desc.pb.go
  pkg/firmament/resource_stats.pb.go
  pkg/firmament/resource_topology_node_desc.pb.go
  pkg/firmament/resource_vector.pb.go
  pkg/firmament/scheduling_delta.pb.go
  pkg/firmament/task_desc.pb.go
  pkg/firmament/task_desc.proto
  pkg/firmament/task_final_report.pb.go
  pkg/firmament/task_stats.pb.go
  pkg/firmament/whare_map_stats.pb.go
  pkg/k8sclient/BUILD
  pkg/k8sclient/podwatcher.go
  pkg/k8sclient/podwatcher_test.go
  pkg/k8sclient/types.go
  test/e2e/framework/BUILD
  test/e2e/framework/util.go
  test/e2e/poseidon_integration.go
  test/e2e/predicates.go
  vendor/github.com/jinzhu/copier/BUILD
  vendor/github.com/jinzhu/copier/Guardfile
  vendor/github.com/jinzhu/copier/License
  vendor/github.com/jinzhu/copier/README.md
  vendor/github.com/jinzhu/copier/copier.go
  vendor/github.com/jinzhu/copier/wercker.yml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#95 replace string with corresponding const
  pkg/k8sclient/nodewatcher.go
  pkg/k8sclient/podwatcher.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#91 add e2e test on memory cost
  test/e2e/poseidon_integration.go
  test/e2e/predicates.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#108 Adding security contact file for poseidon repo
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#109 Adding code of conduct file
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
