Repository kubernetes-sigs/poseidon, pull requests merged in 2018-11, with the labels that each got.

#148 Gang scheduling feature
  deploy/gang-scheduling/gang-scheduling.md
  deploy/gang-scheduling/gang_schedule_test_case_one.yaml
  deploy/gang-scheduling/gang_schedule_test_case_two.yaml
  deploy/gang-scheduling/sample
  pkg/firmament/firmament_scheduler.pb.go
  pkg/firmament/job_desc.pb.go
  pkg/firmament/job_desc.proto
  pkg/firmament/resource_desc.pb.go
  pkg/firmament/resource_vector.pb.go
  pkg/firmament/task_desc.pb.go
  pkg/k8sclient/podwatcher.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#147 Fixed an issue in events
  pkg/k8sclient/events.go
  test/e2e/framework/BUILD
  test/e2e/framework/events.go
  test/e2e/poseidon_integration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#149 Poseidon behave like default scheduler
  pkg/config/config.go
  pkg/k8sclient/podwatcher.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#151 Fix typos: initialze->initialize, previsou->previous
  pkg/firmament/scheduling_delta.pb.go
  pkg/firmament/scheduling_delta.proto
  pkg/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#152 Update the readme and added docs to run poseidon as default scheduler
  docs/devel/README.md
  docs/install/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#153 Adding poseidon design markdown file
  README.md
  docs/design/README.md
  docs/design/images/fig_five.png
  docs/design/images/fig_four.png
  docs/design/images/fig_one.png
  docs/design/images/fig_three.png
  docs/design/images/fig_two.png
  docs/install/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
