Repository kubernetes-sigs/poseidon, pull requests merged in 2018-04, with the labels that each got.

#31 Fix hack/verify-go(lint,vet).sh
  Godeps/Godeps.json
  docs/devel/README.md
  hack/.golint_failures
  hack/lib/golang.sh
  hack/verify-godeps.sh
  hack/verify-golint.sh
  pkg/k8sclient/k8sclient.go
  pkg/k8sclient/nodewatcher.go
  pkg/k8sclient/nodewatcher_test.go
  pkg/k8sclient/podwatcher.go
  pkg/k8sclient/podwatcher_test.go
  pkg/k8sclient/types.go
  pkg/stats/poseidonstats_service_mock.go
  pkg/stats/stats.go
  pkg/stats/stats_test.go
  poseidon.go
  third_party/forked/shell2junit/sh2ju.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#33 Add bazel verify and update scripts
  hack/update-bazel.sh
  hack/verify-bazel.sh
  test/e2e/BUILD
  test/e2e/poseidon_integration_tests.go
  test/e2e/poseidon_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#26 Add update gofmt script
  hack/update-gofmt.sh
  pkg/stats/stats_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#39 Updating Owner file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 Fix golint in k8sclient
  pkg/k8sclient/k8sclient.go
  pkg/k8sclient/keyed_queue.go
  pkg/k8sclient/nodewatcher.go
  pkg/k8sclient/nodewatcher_test.go
  pkg/k8sclient/podwatcher.go
  pkg/k8sclient/podwatcher_test.go
  pkg/k8sclient/types.go
  pkg/k8sclient/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#45 Auto generate kKUBE_GIT_COMMIT for tagging docker image
  build/lib/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#46 Build poseidon image from scratch and explicitly EXPOSE 9091 port
  image/Dockerfile
  image/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S
